//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaVetWF.Utils
{
    using ClinicaVetWF.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_clinicaEntities1 : DbContext
    {
        public db_clinicaEntities1()
            : base("name=db_clinicaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<animal> animal { get; set; }
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<consulta> consulta { get; set; }
        public virtual DbSet<endereco> endereco { get; set; }
        public virtual DbSet<especie> especie { get; set; }
        public virtual DbSet<exame> exame { get; set; }
        public virtual DbSet<formas_pagamento> formas_pagamento { get; set; }
        public virtual DbSet<funcionario> funcionario { get; set; }
        public virtual DbSet<item_venda> item_venda { get; set; }
        public virtual DbSet<medicacao> medicacao { get; set; }
        public virtual DbSet<pagamentos> pagamentos { get; set; }
        public virtual DbSet<pagamentos_parcelados> pagamentos_parcelados { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<venda> venda { get; set; }
    }
}
